# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
              [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[5,6,7],
              [7,2,8],
              [4,1,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[5, 6, 7],
        [7, 2, 8],
        [4, 1, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.dtype , a1.shape ,a1.ndim ,a1.size, type(a1)

(dtype('int64'), (3,), 1, 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape , a2.size , a2.dtype , type(a2), a2.ndim

((2, 3), 6, dtype('int64'), numpy.ndarray, 2)

In [6]:
# Attributes of 3-dimensional array
a3.shape , a3.size, a3.dtype, type(a3) ,a3.ndim

((2, 3, 3), 18, dtype('int64'), numpy.ndarray, 3)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df = pd.DataFrame(a2, columns=['num','value','int'])
df

num  value  int
0    1      2    3
1    4      5    6

In [8]:
# Create an array of shape (10, 2) with only ones
only_ones = np.ones((10,2))
only_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
a = np.arange(0,100,3)
a


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
b = np.random.randint(10 ,size=(7,2))
b

array([[1, 1],
       [3, 0],
       [2, 2],
       [2, 2],
       [9, 8],
       [3, 2],
       [4, 1]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float = np.random.random((3,5))
float 

array([[0.54325358, 0.22098452, 0.05780893, 0.4946335 , 0.41411578],
       [0.75260079, 0.15329178, 0.25509995, 0.66750979, 0.08560827],
       [0.48066486, 0.74539569, 0.20085757, 0.77932286, 0.66575681]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
e =np.random.randint(10 , size=(4,6))
e

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
va = np.random.randint(1,10 , size=(3,7))
va

# Find the unique numbers in the array you just created
va1 = np.unique(va)
va1

array([1, 2, 3, 4, 5, 7, 9])

In [15]:
# Find the 0'th index of the latest array you created
va[0]

array([9, 1, 3, 7, 4, 9, 3])

In [16]:
# Get the first 2 rows of latest array you created
va[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
va[:2, :2]

array([[9, 1],
       [5, 3]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ab = np.random.randint(0,10 ,size =(3,5))
o = np.ones((3,5))

o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Add the two arrays together
abo = ab + o
abo

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [20]:
# Create another array of ones of shape (5, 3)
o2 = np.ones((5,3))

In [21]:
# Try add the array of ones and the other most recent array together
ab3 = o + o2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

i'll transpose the one array as it is (3,5) or (5,3).
we use "transpose()" function


In [ ]:
# Create another array of ones of shape (3, 5)
o3 = np.ones((3,5))

In [ ]:
# Subtract the new array of ones from the other most recent array
ab4 = abo - o3 
ab4

In [ ]:
# Multiply the ones array with the latest array
mul = ab4 * o
mul

In [ ]:
# Take the latest array to the power of 2 using '**'
sq = lambda x: x**2
sq(mul)

In [ ]:
# Do the same thing with np.square()
np.square(mul)

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(mul)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(mul)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(mul)

In [ ]:
# Find the standard deviation of the latest array
np.std(mul)

In [ ]:
# Find the variance of the latest array
np.var(mul)

In [ ]:
# Reshape the latest array to (3, 5, 1)
mul.reshape(3,5,1)

In [ ]:
# Transpose the latest array
np.transpose(mul)

What does the transpose do?

transpose converts the row in column and vice versa 
example: we have (3,2) matrix after using transpose function we have (2,3) matrix

In [22]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ra1 = np.random.randint(10,size = (3,3))
ra2 = np.random.randint(10, size =(3,2))

In [23]:
# Perform a dot product on the two newest arrays you created
ra3 = np.dot(ra1,ra2)
ra3


array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [24]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
va2 = np.random.randint(10 , size =(4,3))
va3 = np.random.randint(10, size = (4,3))

In [25]:
# Perform a dot product on the two newest arrays you created
va4 = np.dot(va2,va3)
va4

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

we can fix it by transposing the one matrix 

In [26]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
va2.T.shape
va4 = np.dot(va2.T,va3)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [32]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
shape = (3,3)
l = np.random.randint(10, size = (shape))
m = np.random.randint(10, size = (shape))
l , m

(array([[0, 2, 9],
        [7, 5, 7],
        [8, 3, 0]]),
 array([[0, 9, 3],
        [6, 1, 2],
        [0, 4, 0]]))

In [33]:
# Compare the two arrays with '>'
m > l

array([[False,  True, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

it checks wether the m is greater than l or not 

In [ ]:
# Compare the two arrays with '>='
l >= m

In [30]:
# Find which elements of the first array are greater than 7
elementGreaterThan7 = l[l>7]
elementGreaterThan7


array([9, 9])

In [34]:
# Which parts of each array are equal? (try using '==')
l == m

array([[ True, False, False],
       [False, False, False],
       [False, False,  True]])

In [36]:
# Sort one of the arrays you just created in ascending order
np.sort(l)

array([[0, 2, 9],
       [5, 7, 7],
       [0, 3, 8]])

In [38]:
# Sort the indexes of one of the arrays you just created
np.argsort(l)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]])

In [41]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(l)

print(max_index)


2


In [43]:
# Find the index with the minimum value in one of the arrays you've created
min_index =np.argmin(l)
print(min_index)

0


In [46]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
abo_max = np.argmax(abo , axis =1)
print(abo_max)

[1 1 1]


In [47]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
abo_min = np.argmin(abo , axis=0)
print(abo_min)

[1 0 0 0 2]


In [56]:
# Create an array of normally distributed random numbers
a = np.random.normal(1,10,2)
print(a)

[ 0.19912665 -1.41380132]


In [57]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ls = np.linspace(0,1,10)
print(ls)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.
